"""Export POM's valid <Icon name> values -> src/knowledge/core/icon-names.txt.

The installed compiler is the source of truth (ICON_DATA in
@hirokisakabe/pom/dist/icons/iconData.js). The normalizer reads the exported
list to drop unknown icons before compile. Re-run after upgrading POM:

    python -m scripts.export_icon_names
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

_PIPELINE_ROOT = Path(__file__).resolve().parent.parent
_POM_DIR = _PIPELINE_ROOT / "src" / "node" / "node_modules" / "@hirokisakabe" / "pom"
_OUT = _PIPELINE_ROOT / "src" / "knowledge" / "core" / "icon-names.txt"

_JS = (
    "const {ICON_DATA} = await import(process.argv[1]);"
    "console.log(Object.keys(ICON_DATA).join('\\n'));"
)


def main() -> int:
    icon_data = _POM_DIR / "dist" / "icons" / "iconData.js"
    if not icon_data.exists():
        print(f"POM not installed: {icon_data} missing. Run: npm install --prefix src/node")
        return 1
    version = json.loads((_POM_DIR / "package.json").read_text(encoding="utf-8"))["version"]
    out = subprocess.run(
        ["node", "--input-type=module", "-e", _JS, icon_data.as_uri()],
        capture_output=True, text=True, check=True,
    ).stdout
    names = sorted({n.strip() for n in out.splitlines() if n.strip()})
    header = (
        f"# Valid <Icon name> values for @hirokisakabe/pom {version} ({len(names)} names).\n"
        "# GENERATED by scripts/export_icon_names.py — do not edit by hand.\n"
    )
    _OUT.write_text(header + "\n".join(names) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(names)} icon names -> {_OUT.relative_to(_PIPELINE_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
