"""Regenerate tests/cases/gj-h1-regen.yaml from the golden gj-h1 deck (DECIDE 2026-09-23).

The request holds only the golden deck's content — every text, table row and chart
series per slide, in reading order — never its layout, so the pipeline must design
the slides itself. eval_run scores the result against the golden deck (`golden:`).

    python -m scripts.make_gj_h1_case
"""

from __future__ import annotations

import re
from pathlib import Path
from xml.etree import ElementTree as ET

import yaml

_PIPELINE_ROOT = Path(__file__).resolve().parent.parent
GOLDEN = Path("tests/fixtures/golden/gj-h1-deck")
CASE = _PIPELINE_ROOT / "tests" / "cases" / "gj-h1-regen.yaml"


def _text(el: ET.Element) -> str:
    return re.sub(r"\s+", " ", "".join(el.itertext())).strip()


def slide_content(xml: str) -> list[str]:
    slide = ET.fromstring(xml[xml.index("<Slide"):])
    lines: list[str] = []

    def walk(el: ET.Element) -> None:
        if el.tag in ("Text", "Li", "Shape"):
            if t := _text(el):
                lines.append(t)
        elif el.tag == "Table":
            lines.extend(" | ".join(_text(td) for td in tr) for tr in el.iter("Tr"))
        elif el.tag == "Chart":
            lines.append(f"Chart ({el.get('chartType')}):")
            for s in el.iter("ChartSeries"):
                points = ", ".join(f"{p.get('label')} {p.get('value')}" for p in s.iter("ChartDataPoint"))
                lines.append(f"  {s.get('name')}: {points}")
        else:
            for child in el:
                walk(child)

    walk(slide)
    return lines


def build_case() -> str:
    parts = []
    for i, path in enumerate(sorted((_PIPELINE_ROOT / GOLDEN).glob("*.xml")), 1):
        body = "\n".join(slide_content(path.read_text(encoding="utf-8")))
        parts.append(f"Slide {i}:\n{body}")
    case = {
        "name": "gj-h1-regen",
        "objective": ("Regenerate the 14-slide golden gj-h1 deck from its content only; "
                      "scored per slide against the golden deck (card patterns, fill ratio, audit)."),
        "request": ("Create a 14-slide Q-commerce performance review deck, one slide per section below, "
                    "using exactly this data (verbatim numbers):\n\n" + "\n\n".join(parts)),
        "content_source": "fully supplied (extracted from the golden deck by scripts/make_gj_h1_case.py)",
        "golden": GOLDEN.as_posix(),
        "expect": {"compiles": True, "slide_count": 14},
    }
    header = "# GENERATED by scripts/make_gj_h1_case.py from tests/fixtures/golden/gj-h1-deck — do not edit.\n"
    return header + yaml.safe_dump(case, sort_keys=False, allow_unicode=True, width=120)


def main() -> int:
    CASE.write_text(build_case(), encoding="utf-8")
    print(f"wrote {CASE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
